version: '3.8'

services:
  lab_14_3:
    build: .
    container_name: lab_14_3
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/workspace/src
      - ./launch:/workspace/launch
    network_mode: host
    stdin_open: true
    tty: true
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /workspace/install/setup.bash &&
               sleep 5 &&
               bash"
